# Generated by Django 6.0.7 on 2026-07-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_must_change_password'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='admin_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leave',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['status'], name='leave_leave_status_34d281_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['employee'], name='leave_leave_employe_5dece3_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['start_date'], name='leave_leave_start_d_cb7d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['end_date'], name='leave_leave_end_dat_0c9798_idx'),
        ),
    ]
